C: 100
DATASET_PATH: ./data_mini/golden_884_set.csv
kernel: linear
label: '[''import'', ''data_import'', ''data_export'', ''preprocessing'', ''visualization'',
  ''model'', ''deep_learning_model'', ''train'', ''predict'']'
max_df: 0.3
min_df: 5
model: ./models/nurx2/svm_regex.sav
nrows: 884
random_state: 241
script_dir: svm_train.py
smooth_idf: true
