DATASET_PATH: ./data/code_blocks_clean_regex_graph_v6.csv
MODEL_DIR: ./models/logreg_regex_graph_v6.sav
TFIDF_DIR: ./models/tfidf_logreg_graph_v6.pickle
graph_ver: 6
label: '[''import'', ''data_import'', ''data_export'', ''preprocessing'', ''visualization'',
  ''model'', ''deep_learning_model'', ''train'', ''predict'']'
max_df: 0.3
min_df: 5
nrows: 225565
script_dir: logreg_classifier.ipynb
smooth_idf: true
task: training LogReg
