context:
  context_size: 16
data:
  DATASET_PATH: ../data/context_clean_markup_data_2021-05-06.csv
  label: '[''Hypothesis.statistical_test'', ''Hyperparam_Tuning.choose_model_class'',
    ''Hypothesis.pipeline_type_spec'', ''Environment.import_modules'', ''Environment.set_options'',
    ''Environment.get_options'', ''Data_Extraction.load_from_url'', ''Data_Extraction.load_from_sql'',
    ''Data_Extraction.load_from_disk'', ''Data_Extraction.load_from_csv'', ''EDA.show_table'',
    ''EDA.show_table_attributes'', ''EDA.count_missing_values'', ''EDA.count_duplicates'',
    ''EDA.count_data_types'', ''EDA.count_unique_values'', ''EDA.get_unique_values'',
    ''EDA.show_shape'', ''Data_Transform.create_dataframe'', ''Data_Transform.remove_duplicates'',
    ''Data_Transform.correct_missing_values'', ''Data_Transform.normalization'', ''Data_Transform.data_type_conversions'',
    ''Data_Transform.randomize_order'', ''Data_Transform.split'', ''Data_Transform.filter'',
    ''Data_Transform.concatenate'', ''Data_Transform.drop_column'', ''Data_Transform.sort_values'',
    ''Data_Transform.feature_engineering'', ''Data_Transform.to_dummies'', ''Data_Transform.prepare_x_and_y'',
    ''Data_Transform.categorify'', ''Data_Transform.augment'', ''Data_Transform.merge'',
    ''Data_Transform.groupby'', ''Data_Transform.rename_columns'', ''Model_Train.choose_model_class'',
    ''Model_Train.train_model'', ''Model_Train.metric_computation'', ''Model_Train.predict'',
    ''Model_Train.load_pretrained'', ''Model_Train.init_hyperparams'', ''Model_Evaluation.compute_test_metric'',
    ''Model_Evaluation.predict_on_test'', ''Model_Interpretation.get_coefficients'',
    ''Hyperparam_Tuning.find_best_score'', ''Hyperparam_Tuning.find_best_params'',
    ''Hyperparam_Tuning.find_best_model_class'', ''Hyperparam_Tuning.train_on_grid'',
    ''Hyperparam_Tuning.define_search_space'', ''Hyperparam_Tuning.fit_one_cycle'',
    ''Visualization.learning_history'', ''Visualization.distribution'', ''Visualization.wandb'',
    ''Visualization.missing_values'', ''Visualization.plot_predictions'', ''Data_Export.save_to_csv'',
    ''Production.send_to_prod_environment'', ''Production.save_weights'']'
  model: ../models/catboost_regex_graph_v7.sav
  nrows: 4284
  script_dir: catboost_context.py
kfold:
  n_splits: 3
  random_state: 42
  shuffle: true
model:
  depth: 6
  iterations: 1451
  learning_rate: 0.2113374585744406
  random_seed: 42
  verbose: false
tfidf:
  max_df: 0.20913648057995862
  min_df: 11
  smooth_idf: true
