data:
  DATASET_PATH: ../data/clean_markup_data_2021-05-06.csv
  model: ../models/nbsvm_regex_graph_v7.0.sav
  script_dir: /Users/negativex/School/research/nl2ml/models_scripts/./train_nb_svm.py
kfold:
  n_splits: 10
  random_state: 42
  shuffle: true
model:
  nb:
    alpha: 4.217691433673369
  svc:
    C: 0.5031939994098586
    kernel: linear
    max_iter: 10000
    random_state: 42
tfidf:
  max_df: 0.942478927222569
  min_df: 1
  ngram_range: (1, 2)
  smooth_idf: true
  tokenizer: BPE
