C: 100
DATASET_PATH: ./data_mini/code_blocks_regex_graph_v6.csv
kernel: linear
label: '[''import'', ''data_import'', ''data_export'', ''preprocessing'', ''visualization'',
  ''model'', ''deep_learning_model'', ''train'', ''predict'']'
max_df: 0.3
min_df: 5
model: ./models/svm_regex_graph_v6.sav
nrows: 253909
random_state: 241
script_dir: "/Users/Anna/Desktop/\u0410\u043A\u0442\u0438\u0432\u043D\u043E\u0441\u0442\
  \u0438/NL2ML/nl2ml/svm_train.py"
smooth_idf: true
