GRAPH_VER: 6

regex:
  DATASET_PATH: ./data/code_blocks_clean.csv
  evaluation:

train_logreg:
  DATASET_PATH: ./data/code_blocks_regex_graph_v6.csv

train_svm:
  DATASET_PATH: ./data/code_blocks_regex_graph_v6.csv