DATASET_PATH: ./data/golden_884_set.csv
graph_ver: 6
label: '[''import'', ''data_import'', ''data_export'', ''preprocessing'', ''visualization'',
  ''model'', ''deep_learning_model'', ''train'', ''predict'']'
model: regex_v6
nrows: 884
script_dir: ./regex.ipynb
task: regex evaluation
