data:
  DATASET_PATH: ../data/clean_markup_data_2021-04-28.csv
  model: ../models/rnn_codebert.pt
  random_seed: 42
  script_dir: /Users/negativex/School/research/nl2ml/models_scripts/commit_results.py
model:
  lin_size: 269
  n_classes: 67
  n_rnn_layers: 1
  rnn_size: 180
